skills = [
    {"index": "ACT", "name": "act", "description": "hability to"},
    {"index": "ANTROPOLOGY", "name": "antropology", "description": "hability to"},
    {"index": "ARCHEOLOGY", "name": "archeology", "description": "hability to"},
    {"index": "ART", "name": "art", "description": "hability to"},
    {"index": "MARTIAL_ARTS", "name": "martial arts", "description": "hability to"},
    {"index": "ASTRONOMY", "name": "astronomy", "description": "hability to"},
    {"index": "BIOLOGY", "name": "biology", "description": "hability to"},
    {"index": "DIVING", "name": "diving", "description": "hability to"},
    {"index": "BUROCRACY", "name": "burocracy", "description": "hability to"},
    {"index": "SEARCH_BOOKS", "name": "search books", "description": "hability to"},
    {"index": "LOCKSMITH", "name": "locksmith", "description": "hability to"},
    {"index": "CHARISMA", "name": "charisma", "description": "hability to convince another person to think like you"},
    {"index": "OCULT_SCIENCE", "name": "ocult science", "description": "hability to"},
    {"index": "SURGERY", "name": "surgery", "description": "hability to"},
    {"index": "COMPTOGRAPHY", "name": "comptography", "description": "hability to"},
    {"index": "DRIVING", "name": "driving", "description": "hability to drive every thing that has tires"},
    {"index": "MAQUINARY_DRIVING", "name": "maquinary driving", "description": "hability to"},
    {"index": "MOTORCICLE_DRIVING", "name": "motorcicle driving", "description": "hability to"},
    {"index": "ACCOUNTING", "name": "accounting", "description": "hability to"},
    {"index": "FIX", "name": "fix", "description": "hability to"},
    {"index": "DAMAGE_CONTROL", "name": "damage control", "description": "hability to"},
    {"index": "CREDIT", "name": "credit", "description": "hability to"},
    {"index": "CRIPTOGRAPHY", "name": "criptography", "description": "hability to"},
    {"index": "LAW", "name": "law", "description": "hability to"},
    {"index": "PERCEPTION", "name": "perception", "description": "hability to"},
    {"index": "COSTUME", "name": "costume", "description": "hability to"},
    {"index": "MILITAR_DOCTRINE", "name": "militar doctrine", "description": "hability to"},
    {"index": "ELECTRICITY", "name": "electricity", "description": "hability to"},
    {"index": "COMBAT_TRAINING", "name": "combat training", "description": "hability to"},
    {"index": "EQUITATION", "name": "equitation", "description": "hability to"},
    {"index": "LISTENING", "name": "listening", "description": "hability to"},
    {"index": "SPYING", "name": "spying", "description": "hability to"},
    {"index": "SKYING", "name": "skying", "description": "hability to"},
    {"index": "DODGE", "name": "dodge", "description": "hability to"},
    {"index": "PHARMACOLOGY", "name": "pharmacology", "description": "hability to"},
    {"index": "PHYSIC", "name": "physic", "description": "hability to"},
    {"index": "FOLCLORE", "name": "folclore", "description": "hability to"},
    {"index": "PHOTOGRAPHY", "name": "photography", "description": "hability to"},
    {"index": "PHOTO_INTERPRETATION", "name": "photo interpretation", "description": "hability to"},
    {"index": "GEOLOGY", "name": "geology", "description": "hability to"},
    {"index": "SCROUNGE", "name": "scrounge", "description": "hability to"},
    {"index": "HYPNOSIS", "name": "hypnosis", "description": "hability to"},
    {"index": "HISTORY", "name": "history", "description": "hability to"},
    {"index": "NATURAL_HISTORY", "name": "natural history", "description": "hability to"},
    {"index": "COMBAT_ENGINEER", "name": "combat engineer", "description": "hability to"},
    {"index": "THROW", "name": "throw", "description": "hability to"},
    {"index": "MECHANIC", "name": "mechanic", "description": "hability to"},
    {"index": "MEDICINE", "name": "medicine", "description": "hability to"},
    {"index": "FORENSIC_MEDICINE", "name": "forensic medicine", "description": "hability to"},
    {"index": "METEOROLOGY", "name": "meteorology", "description": "hability to"},
    {"index": "CTHULHU_MYTHS", "name": "cthulhy myths", "description": "hability to"},
    {"index": "SWIMMING", "name": "swimming", "description": "hability to"},
    {"index": "HIDE", "name": "hide", "description": "hability to"},
    {"index": "ORIENTATION", "name": "orientation", "description": "hability to"},
    {"index": "OTHER_LANGUAGES", "name": "other languages", "description": "hability to"},
    {"index": "PARACHUTE", "name": "parachute", "description": "hability to"},
    {"index": "PERSUASION", "name": "persuasion", "description": "hability to"},
    {"index": "PILOT", "name": "pilot", "description": "hability to"},
    {"index": "FIRST_AID", "name": "first aid", "description": "hability to"},
    {"index": "PSYCHOANALYSIS", "name": "psychoanalysis", "description": "hability to"},
    {"index": "PSYCHOLOGY", "name": "psychology", "description": "hability to"},
    {"index": "CHEMISTRY", "name": "chemistry", "description": "hability to"},
    {"index": "BARGAIN", "name": "bargain", "description": "hability to"},
    {"index": "SABOTAGE", "name": "sabotage", "description": "hability to"},
    {"index": "JUMP", "name": "jump", "description": "hability to"},
    {"index": "FOLLOW_HINTS", "name": "follow hints", "description": "hability to"},
    {"index": "AERONAUTIC_SYSTEMS", "name": "aeronautic systems", "description": "hability to"},
    {"index": "SURVIVAL", "name": "survival", "description": "hability to"},
    {"index": "TACTICS", "name": "tactics", "description": "hability to"},
    {"index": "PHONE", "name": "phone", "description": "hability to"},
    {"index": "TEOLOGY", "name": "teology", "description": "hability to"},
    {"index": "CLIMB", "name": "climb", "description": "hability to"},
    {"index": "RADIO_USE", "name": "radio use", "description": "hability to"},
    {"index": "SHORT_WEAPON", "name": "short weapon", "description": "hability to use short fire weapons"},
    {"index": "FALSIFICATION", "name": "falsification", "description": "hability to falsificate succesfully"},
    {"index": "STEALTH", "name": "stealth", "description": "hability to stay out of sight"}
]